import { Link } from "react-router-dom";
import { motion } from "motion/react";
import { ArrowLeft, ExternalLink } from "lucide-react";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from "recharts";
import Navbar from "../../components/Navbar";
import { businessRevenueByYear, businessRevenueSources } from "../../data/businessRevenueData";

export default function BusinessRevenuePage() {
  return (
    <div className="dot-grid min-h-screen pt-28 px-4 pb-16">
      <Navbar />
      <div className="max-w-4xl mx-auto">
        <Link
          to="/explore/business-entrepreneurship"
          className="flex items-center gap-2 text-accent text-sm mb-6"
        >
          <ArrowLeft size={16} />
          Back to Business and Entrepreneurship
        </Link>

        <p className="text-accent text-xs uppercase tracking-widest mb-2">
          Business and Entrepreneurship
        </p>
        <h1 className="text-3xl md:text-4xl font-heading font-bold text-white mb-3">
          Business Revenues
        </h1>
        <p className="text-muted mb-8 max-w-2xl">
          Total revenue generated by all formal-sector establishments in the Philippines rose
          from ₱17.90 trillion in 2017 to ₱23.57 trillion in 2022, according to PSA's Annual
          Survey of Philippine Business and Industry (ASPBI). The bars aren't evenly spaced in
          time — see the note below the chart for why some years are missing.
        </p>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="glass-card p-6 mb-4"
        >
          <ResponsiveContainer width="100%" height={360}>
            <BarChart data={businessRevenueByYear}>
              <CartesianGrid strokeDasharray="3 3" stroke="#27384E" />
              <XAxis dataKey="year" stroke="#9FB3C8" />
              <YAxis stroke="#9FB3C8" tickFormatter={(v) => `₱${v}T`} />
              <Tooltip
                contentStyle={{ background: "#0E1B2C", border: "1px solid #27384E" }}
                cursor={{ fill: "#2DD4BF", fillOpacity: 0.06 }}
                formatter={(value) => [`₱${Number(value).toFixed(2)}T`, "Total revenue"]}
              />
              <Bar dataKey="revenueTrillionPHP" fill="#2DD4BF" radius={[6, 6, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </motion.div>

        <p className="text-footnote text-xs mb-10">
          2018 was a Census of Philippine Business and Industry year rather than an ASPBI annual
          survey — a different, exhaustive-count methodology — so it's excluded here to avoid
          mixing the two. 2016's total could not be confirmed from a primary source. 2020 and
          2021 are ASPBI final results; 2022 is the latest preliminary result PSA had released as
          of this writing, with nothing yet published for 2023 or later.
        </p>

        <h2 className="text-xl font-heading font-bold text-white mb-4">Full data</h2>
        <div className="glass-card overflow-x-auto mb-10">
          <table className="w-full text-sm text-left">
            <thead className="text-muted border-b border-grid">
              <tr>
                <th className="p-4">Year</th>
                <th className="p-4">Total Revenue</th>
                <th className="p-4">Formal-Sector Establishments</th>
              </tr>
            </thead>
            <tbody>
              {businessRevenueByYear.map((row) => (
                <tr key={row.year} className="border-b border-grid/50">
                  <td className="p-4 font-semibold text-white">{row.year}</td>
                  <td className="p-4">₱{row.revenueTrillionPHP.toFixed(2)} trillion</td>
                  <td className="p-4">
                    {row.establishments !== null ? row.establishments.toLocaleString() : "—"}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <h2 className="text-xl font-heading font-bold text-white mb-2">Sources</h2>
        <div className="space-y-4 mb-10">
          {businessRevenueSources.map((source) => (
            <div key={source.url} className="glass-card p-4">
              <div className="flex items-start justify-between gap-3">
                <a
                  href={source.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-2 text-accent font-semibold hover:underline"
                >
                  {source.title}
                  <ExternalLink size={14} />
                </a>
                <span className="text-xs px-2 py-1 rounded-full whitespace-nowrap bg-accent/20 text-accent">
                  Primary source
                </span>
              </div>
              <p className="text-footnote text-xs mt-1">
                {source.publisher} — {source.date}
              </p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
